PREFIX : <http://biobeat.org/rdf/ns#chr>
SELECT ?BeerName ?Perc ?Country ?Continent ?Size
WHERE
{
  ?BEER :Continent "Europe";
        :Name ?BeerName ;
        :Alc_percentage ?Perc ;
	:Country ?Country ;
	:Continent ?Continent ;
	:Bottle_size_ml ?Size .
  FILTER(?Size >=400 || ?Perc >=7).
}
